import { Project } from "@/types/portfolio";

export const academicProjects: Project[] = [
  {
    id: "tidescape",
    title: "TIDESCAPE",
    slug: "tidescape",
    category: "academic",
    categories: ["academic", "selected"],
    gridPos: { x: 1, y: 1 },
    subtitle: "Academic • Diploma Project — Library & Research Center",
    year: "2024",
    location: "Istanbul / Besiktas",
    coverImage: {
      url: "/projects/academic/tidescape/cover/cover.png",
      alt: "Tidescape flow diagram and urban coastal masterplan",
      aspectRatio: "16/9",
    },
    gallery: [
      {
        url: "/projects/academic/tidescape/gallery/PORTFOLYO2025_A33.jpg",
        alt: "Tidescape Project Title Cover Plate",
        caption: "Parti Title & Master Urban Strategy Overview.",
      },
      {
        url: "/projects/academic/tidescape/gallery/PORTFOLYO2025_A34.jpg",
        alt: "Beşiktaş Urban Masterplan & Contextual Strategy",
        caption: "Site analysis connecting Beşiktaş Square, ferry terminals, and Bosphorus shoreline.",
      },
      {
        url: "/projects/academic/tidescape/gallery/PORTFOLYO2025_A35.jpg",
        alt: "Elevated promenade & archeological ruins integration",
        caption: "Continuous public walkway bridging urban pedestrian transit with coastal heritage.",
      },
      {
        url: "/projects/academic/tidescape/gallery/PORTFOLYO2025_A36.jpg",
        alt: "Curvilinear Waterfront Piers & Stepped Public Seating",
        caption: "Stepped waterfront viewing piers designed for varied coastal tidal interactions.",
      },
      {
        url: "/projects/academic/tidescape/gallery/PORTFOLYO2025_A37.jpg",
        alt: "Urban Circulation & Programmatic Axonometric",
        caption: "Volumetric massing distribution around permeable central courtyard.",
      },
      {
        url: "/projects/academic/tidescape/gallery/PORTFOLYO2025_A38.jpg",
        alt: "Transverse Building Cross-Section A-A",
        caption: "Architectural section illustrating programmatic layers and daylighting strategy.",
      },
      {
        url: "/projects/academic/tidescape/gallery/PORTFOLYO2025_A39.jpg",
        alt: "Ground Level Public Access & Library Floor Plan",
        caption: "Detailed ground floor plan with reading rooms, exhibition galleries, and courtyards.",
      },
    ],
    description:
      "TIDESCAPE focuses on Beşiktaş Square as both a dynamic transport hub and a static cultural coastline. The design strengthens the relationship between the Bosphorus and the city core through elevated walkways, public courtyards, and curvilinear waterfront piers.",
    fullStory:
      "The registered buildings and historical ruins in the project area played a defining role in the massing design. High volumes are positioned away from the shoreline to maintain coastal openness, while lower volumes gather around a permeable public courtyard. Ramps and staircases connect the shore to walkable terrace roofs, offering uninterrupted views of the Bosphorus.",
    technicalSpecs: [
      { label: "Type", value: "Academic • Diploma Project" },
      { label: "Program", value: "Library & Research Center" },
      { label: "Location", value: "Beşiktaş, Istanbul" },
      { label: "Year", value: "2024" },
    ],
    featured: true,
    tags: ["Academic", "Diploma", "Public Realm", "Bosphorus", "Heritage Integration", "Selected"],
  },
  {
    id: "pb-workshop",
    title: "PB WORKSHOP",
    slug: "pb-workshop",
    category: "academic",
    categories: ["academic", "selected"],
    gridPos: { x: 5, y: 0 },
    subtitle: "Academic • Workshop & Conference Hall",
    year: "2023",
    location: "Istanbul / Beyoglu",
    coverImage: {
      url: "/projects/academic/pb-workshop/cover/PORTFOLYO2025_A310.jpg",
      alt: "PB Workshop street analysis and Kurşunlu Han diagram",
      aspectRatio: "16/9",
    },
    gallery: [
      {
        url: "/projects/academic/pb-workshop/gallery/PORTFOLYO2025_A310.jpg",
        alt: "PB Workshop Project Title Cover Plate",
        caption: "Perşembepazarı Urban Regeneration & Kurşunlu Han Context.",
      },
      {
        url: "/projects/academic/pb-workshop/gallery/PORTFOLYO2025_A311.jpg",
        alt: "Beyoğlu Urban Masterplan & Street Permeability",
        caption: "Urban diagram linking Tersane Street, hardware bazaar, and Golden Horn coastline.",
      },
      {
        url: "/projects/academic/pb-workshop/gallery/PORTFOLYO2025_A312.jpg",
        alt: "Four Building Masses & Skybridge Network",
        caption: "Massing strategy preserving traditional inn-courtyard morphology.",
      },
      {
        url: "/projects/academic/pb-workshop/gallery/PORTFOLYO2025_A313.jpg",
        alt: "Ground Floor Public Passage & Courtyard Plan",
        caption: "Pedestrian thoroughfare carving open spaces between workshop blocks.",
      },
      {
        url: "/projects/academic/pb-workshop/gallery/PORTFOLYO2025_A314.jpg",
        alt: "Maker Workshops & Digital Fabrication Floor Plans",
        caption: "Programmatic layout for collaborative metal, wood, and digital craft workshops.",
      },
      {
        url: "/projects/academic/pb-workshop/gallery/PORTFOLYO2025_A315.jpg",
        alt: "Conference Hall & Auditorium Tiered Layout",
        caption: "Multipurpose auditorium integrating acoustic paneling and natural skylights.",
      },
    ],
    description:
      "Situated in Perşembepazarı, Beyoğlu, PB Workshop revitalizes the architectural and sociocultural heritage of the historical 'Kurşunlu Han'.",
    fullStory:
      "The mass concept continues the traditional inn-bazaar-courtyard archetype. Four distinct building masses linked by elevated bridges are lifted above ground level to create permeable pedestrian passages between Tersane Street and the Golden Horn waterfront.",
    technicalSpecs: [
      { label: "Type", value: "Academic Project" },
      { label: "Program", value: "Workshop & Conference Hall" },
      { label: "Location", value: "Perşembepazarı, Beyoğlu, Istanbul" },
      { label: "Year", value: "2023" },
    ],
    featured: true,
    tags: ["Academic", "Heritage", "Beyoğlu", "Courtyard Urbanism", "Selected"],
  },
  {
    id: "canography",
    title: "CANOGRAPHY",
    slug: "canography",
    category: "academic",
    categories: ["academic", "selected"],
    gridPos: { x: 8, y: 2 },
    subtitle: "Academic • Canoe Club & Archive",
    year: "2021",
    location: "Istanbul / Fatih",
    coverImage: {
      url: "/projects/academic/canography/cover/PORTFOLYO2025_A316.jpg",
      alt: "Canography physical model photo showing organic ribbons",
      aspectRatio: "16/9",
    },
    gallery: [
      {
        url: "/projects/academic/canography/gallery/PORTFOLYO2025_A316.jpg",
        alt: "Canography Project Title Cover Plate",
        caption: "Canoe Club & Kinetic Energy Archive at Golden Horn Metro Bridge.",
      },
      {
        url: "/projects/academic/canography/gallery/PORTFOLYO2025_A317.jpg",
        alt: "Metro Bridge & Coastal Infrastructure Site Map",
        caption: "Urban vibration recovery strategy across subway, tramway, and vehicular lanes.",
      },
      {
        url: "/projects/academic/canography/gallery/PORTFOLYO2025_A318.jpg",
        alt: "Piezoelectric Harvesting Mechanism Diagrams",
        caption: "Translating mechanical vibration energy from bridge piers into electrical power.",
      },
      {
        url: "/projects/academic/canography/gallery/PORTFOLYO2025_A319.jpg",
        alt: "Breakwater Foundation & Energy Core Cut",
        caption: "Subterranean energy archive integrated directly inside breakwater caissons.",
      },
    ],
    description:
      "Located at the Golden Horn metro coastal intersection in Fatih, Canography recovers energy lost during subway infrastructure construction.",
    fullStory:
      "The building converts urban vibration energy generated by tramways, vehicular avenues, and foot traffic into electricity using embedded piezo systems. Integrated into the subway breakwaters, the structure functions as both an active canoe club and a public energy archive.",
    technicalSpecs: [
      { label: "Type", value: "Academic Project" },
      { label: "Program", value: "Canoe Club & Archive" },
      { label: "Location", value: "Fatih, Golden Horn, Istanbul" },
      { label: "Innovation", value: "Piezoelectric Energy Harvesting" },
    ],
    featured: false,
    tags: ["Kinetic Architecture", "Piezo Energy", "Waterfront", "Fatih", "Selected"],
  },
  {
    id: "roboshore",
    title: "ROBOSHORE",
    slug: "roboshore",
    category: "academic",
    categories: ["academic", "selected"],
    gridPos: { x: 3, y: 3 },
    subtitle: "Competition • Jury Special Award — Urban Design",
    year: "2023",
    location: "Istanbul",
    coverImage: {
      url: "/projects/academic/roboshore/cover/PORTFOLYO2025_A320.jpg",
      alt: "Roboshore axonometric of floating modules along shoreline",
      aspectRatio: "16/9",
    },
    gallery: [
      {
        url: "/projects/academic/roboshore/gallery/PORTFOLYO2025_A320.jpg",
        alt: "Roboshore Jury Special Award Title Plate",
        caption: "AI-Driven Temporary Robotic Urban Shoreline Injection System.",
      },
      {
        url: "/projects/academic/roboshore/gallery/PORTFOLYO2025_A321.jpg",
        alt: "Haliç Shipyard Territorial Site Strategy",
        caption: "Mapping public space deficits along Golden Horn historical industrial shores.",
      },
      {
        url: "/projects/academic/roboshore/gallery/PORTFOLYO2025_A322.jpg",
        alt: "42cm x 42cm Modular Glulam Unit Architecture",
        caption: "Parametric interlocking timber joint requiring zero mechanical fasteners.",
      },
    ],
    description:
      "Jury Special Award-winning competition proposal for an adaptive, temporary urban shoreline injection system along the Golden Horn.",
    fullStory:
      "Roboshore synthesizes urban data through AI to deploy temporary, lightweight public intervention units. Utilizing 42cm × 42cm modular glulam components, robotic constructor arms assemble floating public spaces on polyethylene barges that adapt dynamically to neighborhood events.",
    technicalSpecs: [
      { label: "Award", value: "Jury Special Award" },
      { label: "Program", value: "Urban Design" },
      { label: "Team", value: "Ezgi Özdil, Andaç Güney, Berkan Sarı, Atalay Fersiz" },
      { label: "Location", value: "Haliç Tersane, Istanbul" },
      { label: "Year", value: "2023" },
    ],
    featured: true,
    tags: ["Robotic Construction", "Jury Award", "AI Urbanism", "Parametric", "Selected"],
  },
  {
    id: "amorf",
    title: "AMORF",
    slug: "amorf",
    category: "academic",
    categories: ["academic"],
    gridPos: { x: 0, y: 2 },
    subtitle: "Competition • AMORF Natural Stone Project and Design Competition",
    year: "2023",
    location: "Izmir / Turkey",
    coverImage: {
      url: "/projects/academic/amorf/cover/183E94BDC7.jpg",
      alt: "AMORF Natural Stone Competition Cover",
      aspectRatio: "1/1",
    },
    gallery: [
      {
        url: "/projects/academic/amorf/gallery/183E94BDC7.jpg",
        alt: "AMORF Natural Stone Presentation Plate",
      },
    ],
    description:
      "A conceptual competition entry exploring procedural marble geometry and digital manufacturing for natural stone architectural elements.",
    technicalSpecs: [
      { label: "Competition", value: "AMORF Natural Stone" },
      { label: "Program", value: "Product & Architectural Design" },
      { label: "Year", value: "2023" },
    ],
    tags: ["Competition", "AMORF", "Natural Stone", "Parametric"],
  },
  {
    id: "kairo-looro",
    title: "KAIRA LOORO",
    slug: "kairo-looro",
    category: "academic",
    categories: ["academic"],
    gridPos: { x: 4, y: 1 },
    subtitle: "Competition • Primary School in Africa — Kaira Looro",
    year: "2023",
    location: "Sedhiou, Senegal",
    coverImage: {
      url: "/projects/academic/kairo-looro/cover/A1_SARMUHTUR4572.jpg",
      alt: "Kaira Looro Primary School Cover",
      aspectRatio: "1/1",
    },
    gallery: [
      {
        url: "/projects/academic/kairo-looro/gallery/Cover_SARMUHTUR4572.jpg",
        alt: "Kaira Looro School Cover Plate",
      },
      {
        url: "/projects/academic/kairo-looro/gallery/A1_SARMUHTUR4572.jpg",
        alt: "Kaira Looro School Main Presentation Board",
      },
    ],
    description:
      "An environmentally conscious, humanitarian primary school designed for Sedhiou, Senegal, leveraging sustainable vernacular earth construction, natural cross-ventilation, and rainwater collection systems.",
    technicalSpecs: [
      { label: "Competition", value: "Kaira Looro International" },
      { label: "Program", value: "Primary School" },
      { label: "Location", value: "Sedhiou, Senegal" },
      { label: "Year", value: "2023" },
    ],
    tags: ["Competition", "Kaira Looro", "Primary School", "Sustainable Architecture"],
  },
  {
    id: "kartalkaya",
    title: "KARTALKAYA",
    slug: "kartalkaya",
    category: "academic",
    categories: ["academic"],
    gridPos: { x: 2, y: 2 },
    subtitle: "Competition • Kartalkaya Mountain Hotel & Ski Resort",
    year: "2023",
    location: "Kartalkaya, Bolu",
    coverImage: {
      url: "/projects/academic/kartalkaya/cover/PAFTA conv 1.jpeg",
      alt: "Kartalkaya Mountain Hotel Cover",
      aspectRatio: "1/1",
    },
    gallery: [
      {
        url: "/projects/academic/kartalkaya/gallery/PAFTA conv 0.jpeg",
        alt: "Kartalkaya Presentation Plate 1",
      },
      {
        url: "/projects/academic/kartalkaya/gallery/PAFTA conv 1.jpeg",
        alt: "Kartalkaya Presentation Plate 2",
      },
      {
        url: "/projects/academic/kartalkaya/gallery/PAFTA conv 2.jpeg",
        alt: "Kartalkaya Presentation Plate 3",
      },
      {
        url: "/projects/academic/kartalkaya/gallery/PAFTA conv 3.jpeg",
        alt: "Kartalkaya Presentation Plate 4",
      },
      {
        url: "/projects/academic/kartalkaya/gallery/PAFTA conv 4.jpeg",
        alt: "Kartalkaya Presentation Plate 5",
      },
      {
        url: "/projects/academic/kartalkaya/gallery/PAFTA conv 5.jpeg",
        alt: "Kartalkaya Presentation Plate 6",
      },
      {
        url: "/projects/academic/kartalkaya/gallery/PAFTA conv 6.jpeg",
        alt: "Kartalkaya Presentation Plate 7",
      },
      {
        url: "/projects/academic/kartalkaya/gallery/PAFTA conv 7.jpeg",
        alt: "Kartalkaya Presentation Plate 8",
      },
    ],
    description:
      "A high-altitude mountain hotel and recreational resort integrated into the alpine topography of Kartalkaya, Bolu, optimizing snow load distribution, solar heat gain, and sweeping mountain panoramas.",
    technicalSpecs: [
      { label: "Program", value: "Mountain Hotel & Resort" },
      { label: "Location", value: "Kartalkaya, Bolu" },
      { label: "Year", value: "2023" },
    ],
    tags: ["Competition", "Mountain Resort", "Hospitality", "Alpine Architecture"],
  },
  {
    id: "mdc",
    title: "MDC",
    slug: "mdc",
    category: "academic",
    categories: ["academic"],
    gridPos: { x: 9, y: 1 },
    subtitle: "Competition • Miniature Design Competition — Honorable Mention",
    year: "2023",
    location: "Istanbul",
    coverImage: {
      url: "/projects/academic/mdc/cover/754963_01.jpg",
      alt: "MDC Miniature Design Cover",
      aspectRatio: "1/1",
    },
    gallery: [
      {
        url: "/projects/academic/mdc/gallery/754963_01.jpg",
        alt: "MDC Board 01",
      },
      {
        url: "/projects/academic/mdc/gallery/754963_02.jpg",
        alt: "MDC Board 02",
      },
    ],
    description:
      "Honorable Mention-winning micro-scale spatial intervention exploring compact modular living units, kinetic space-saving furniture, and responsive folding surfaces.",
    technicalSpecs: [
      { label: "Award", value: "Honorable Mention" },
      { label: "Competition", value: "MDC Miniature Design" },
      { label: "Year", value: "2023" },
    ],
    tags: ["Competition", "Honorable Mention", "Miniature Design", "Micro Scale"],
  },
  {
    id: "cb",
    title: "SCALES & METHODOLOGIES",
    slug: "cb",
    category: "academic",
    categories: ["academic"],
    gridPos: { x: 2, y: 1 },
    subtitle: "Academic • Collaborative Design Laboratory — M-ARCH-T",
    year: "2025",
    location: "Berlin",
    coverImage: {
      url: "/projects/academic/CB/cover/cover.jpg",
      alt: "Scales & Methodologies Collaborative Design Cover",
      aspectRatio: "16/9",
    },
    gallery: Array.from({ length: 17 }, (_, i) => ({
      url: `/projects/academic/CB/gallery/page_${String(i + 1).padStart(2, "0")}.jpg`,
      alt: `Scales & Methodologies Plate ${i + 1}`,
    })),
    description:
      "A structural and environmental design research framework investigating multi-scalar architectural methodologies across loadbearing trusses, vertical circulation cores, climatic envelope performance, and modular unit typologies.",
    technicalSpecs: [
      { label: "Institution", value: "TU Berlin • M-ARCH-T" },
      { label: "Course", value: "Collaborative Design Laboratory" },
      { label: "Term", value: "WS 25/26" },
      { label: "Location", value: "Berlin, Germany" },
    ],
    tags: ["Academic", "TU Berlin", "M-ARCH-T", "Structural Systems", "Climatic Design"],
  },
  {
    id: "hansapocene",
    title: "HANSAPOCENE",
    slug: "hansapocene",
    category: "academic",
    categories: ["academic", "selected"],
    gridPos: { x: 6, y: 2 },
    subtitle: "Academic • Post-Human Ecological Urbanism in Hansaviertel",
    year: "2025",
    location: "Berlin / Hansaviertel",
    coverImage: {
      url: "/projects/academic/Hansapocene/cover/cover.jpg",
      alt: "Hansapocene Ecological Urbanism Cover",
      aspectRatio: "16/9",
    },
    gallery: Array.from({ length: 24 }, (_, i) => ({
      url: `/projects/academic/Hansapocene/gallery/page_${String(i + 1).padStart(2, "0")}.jpg`,
      alt: `Hansapocene Presentation Plate ${i + 1}`,
    })),
    description:
      "An ecological manifesto and speculative architectural proposal reimagining Berlin's modernist Hansaviertel through the lens of multispecies cohabitation, post-human urbanism, and regenerative biological building assemblies.",
    technicalSpecs: [
      { label: "Team", value: "Alec Jil Agopian, Alice Bussei, Atalay Fersiz, Nicolas Becker, Niklas Florian Schütt, Vinith Babu Gopalakrishnan" },
      { label: "Studio", value: "Beyond Modernism • Vernacular Use(s) of Hansaviertel" },
      { label: "Tutors", value: "Prof. Jörg Stollmann, WM Jeanne Lacour" },
      { label: "Institution", value: "TU Berlin • CUD Chair for Urban Design" },
      { label: "Location", value: "Hansaviertel, Berlin" },
      { label: "Year", value: "2025" },
    ],
    tags: ["Academic", "Hansaviertel", "Berlin", "Ecological Urbanism", "Manifesto", "Selected"],
  },
  {
    id: "if",
    title: "IF",
    slug: "if",
    category: "academic",
    categories: ["academic"],
    gridPos: { x: 8, y: 3 },
    subtitle: "Academic • Architectural Design Studio",
    year: "2024",
    location: "Istanbul / Berlin",
    coverImage: {
      url: "/projects/academic/IF/cover/OzdilEzgi_FersizAtalay conv 9.jpeg",
      alt: "IF Project Architectural Studio Cover",
      aspectRatio: "16/9",
    },
    gallery: [
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 0.jpeg", alt: "IF Plate 0" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 1.jpeg", alt: "IF Plate 1" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 2.jpeg", alt: "IF Plate 2" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 3.jpeg", alt: "IF Plate 3" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 4.jpeg", alt: "IF Plate 4" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 5.jpeg", alt: "IF Plate 5" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 6.jpeg", alt: "IF Plate 6" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 7.jpeg", alt: "IF Plate 7" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 8.jpeg", alt: "IF Plate 8" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 9.jpeg", alt: "IF Plate 9" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 10.jpeg", alt: "IF Plate 10" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 11.jpeg", alt: "IF Plate 11" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 12.jpeg", alt: "IF Plate 12" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 13.jpeg", alt: "IF Plate 13" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 14.jpeg", alt: "IF Plate 14" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 15.jpeg", alt: "IF Plate 15" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 16.jpeg", alt: "IF Plate 16" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 17.jpeg", alt: "IF Plate 17" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 18.jpeg", alt: "IF Plate 18" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 19.jpeg", alt: "IF Plate 19" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 20.jpeg", alt: "IF Plate 20" },
      { url: "/projects/academic/IF/gallery/OzdilEzgi_FersizAtalay conv 21.jpeg", alt: "IF Plate 21" },
    ],
    description:
      "An in-depth architectural studio project investigating spatial thresholds, modular volumetric assemblies, tectonic continuity, and public urban interfaces.",
    technicalSpecs: [
      { label: "Team", value: "Ezgi Özdil, Atalay Fersiz" },
      { label: "Type", value: "Academic Design Studio" },
      { label: "Year", value: "2024" },
    ],
    tags: ["Academic", "Design Studio", "Spatial Thresholds", "Tectonic Assembly"],
  },
  {
    id: "steglitzer-kreisel",
    title: "STEGLITZER KREISEL",
    slug: "steglitzer-kreisel",
    category: "academic",
    categories: ["academic", "selected"],
    gridPos: { x: 4, y: 3 },
    subtitle: "Academic • Adaptive Reuse & Urban Regeneration",
    year: "2026",
    location: "Berlin / Steglitz",
    coverImage: {
      url: "/projects/academic/Steglitzer-Kreisel/cover/cover.jpg",
      alt: "Steglitzer Kreisel Adaptive Reuse Cover",
      aspectRatio: "16/9",
    },
    gallery: Array.from({ length: 11 }, (_, i) => ({
      url: `/projects/academic/Steglitzer-Kreisel/gallery/page_${String(i + 1).padStart(2, "0")}.jpg`,
      alt: `Steglitzer Kreisel Plate ${i + 1}`,
    })),
    description:
      "A transformative adaptive reuse strategy for Berlin's iconic Steglitzer Kreisel high-rise and transit interchange, integrating public civic infrastructure, sustainable mass-timber insertions, and ecological envelope retrofits.",
    technicalSpecs: [
      { label: "Team", value: "Sophie Howard, Atalay Fersiz" },
      { label: "Term", value: "SoSe 26" },
      { label: "Type", value: "Academic Studio Project" },
      { label: "Location", value: "Steglitz, Berlin" },
    ],
    tags: ["Academic", "Steglitzer Kreisel", "Berlin", "Adaptive Reuse", "High-Rise", "Selected"],
  },
];
