import { Project } from "@/types/portfolio";

export const professionalProjects: Project[] = [
  {
    id: "tower-in-kadikoy",
    title: "TOWER IN KADIKOY",
    slug: "tower-in-kadikoy",
    category: "professional",
    categories: ["professional", "selected"],
    gridPos: { x: 2, y: 0 },
    subtitle: "Professional - Dilekci Architects DDA — Mixed Use Tower",
    year: "2024",
    location: "Istanbul / Kadıköy",
    coverImage: {
      url: "/projects/professional/tower-in-kadikoy/cover/PORTFOLYO2025_A323.jpg",
      alt: "Tower in Kadikoy hand sketch and architectural parti",
      aspectRatio: "16/9",
    },
    gallery: [
      {
        url: "/projects/professional/tower-in-kadikoy/gallery/PORTFOLYO2025_A323.jpg",
        alt: "Parti Title & Master Urban Strategy Overview",
        caption: "Bird's eye perspective highlighting urban integration within Rasimpaşa, Kadıköy.",
      },
      {
        url: "/projects/professional/tower-in-kadikoy/gallery/PORTFOLYO2025_A324.jpg",
        alt: "Front street elevation and canopy perspective",
        caption: "Street-level perspective showing the transparent protective canopy spanning historical ruins.",
      },
      {
        url: "/projects/professional/tower-in-kadikoy/gallery/PORTFOLYO2025_A325.jpg",
        alt: "Archaeological park interior view with elevated walkways",
        caption: "Suspended visitor walkways hovering above excavated archaeological heritage ruins.",
      },
      {
        url: "/projects/professional/tower-in-kadikoy/gallery/PORTFOLYO2025_A326.jpg",
        alt: "Archaeological Walkway Ramp Perspective",
        caption: "Elevated glass-railed ramps guiding visitors through the heritage preservation layer.",
      },
      {
        url: "/projects/professional/tower-in-kadikoy/gallery/PORTFOLYO2025_A327.jpg",
        alt: "Dinlenç Sokak Street Level Perspective",
        caption: "Urban street front integrating commercial storefronts with public courtyard access.",
      },
    ],
    description:
      "A vertical mixed-use tower in Rasimpaşa, Kadıköy designed to combine accommodation, commercial, and public spaces above an archeological ruin site.",
    fullStory:
      "The primary architectural challenge was wrapping around extensive historical ruins. A light, transparent canopy was designed to preserve the archeological layer while elevated public ramps allow visitors to view the ruins. AI image generation was integrated into the early sketch workflow to test structural variations rapidly.",
    technicalSpecs: [
      { label: "Firm", value: "Dilekci Architects (DDA)" },
      { label: "Contribution", value: "Phase I, II - Concept Design" },
      { label: "Program", value: "Mixed Use Tower" },
      { label: "Location", value: "Kadıköy, Istanbul" },
      { label: "Year", value: "2024" },
    ],
    featured: true,
    tags: ["Professional", "Dilekci Architects", "Mixed Use", "Concept Design", "Kadıköy", "Selected"],
  },
  {
    id: "tower-in-ihsaniye",
    title: "TOWER IN IHSANIYE",
    slug: "tower-in-ihsaniye",
    category: "professional",
    categories: ["professional", "selected"],
    gridPos: { x: 6, y: 1 },
    subtitle: "Professional - Dilekci Architects DDA — Mixed Use Tower",
    year: "2024",
    location: "Istanbul / Ihsaniye",
    coverImage: {
      url: "/projects/professional/tower-in-ihsaniye/cover/PORTFOLYO2025_A328.jpg",
      alt: "Tower in Ihsaniye architectural sketch and parti drawing",
      aspectRatio: "16/9",
    },
    gallery: [
      {
        url: "/projects/professional/tower-in-ihsaniye/gallery/PORTFOLYO2025_A328.jpg",
        alt: "Parti sketch and Lumion mass render",
        caption: "Wind dynamics and visibility analysis driving the tower's organic curvature.",
      },
      {
        url: "/projects/professional/tower-in-ihsaniye/gallery/PORTFOLYO2025_A329.jpg",
        alt: "Microclimate wind velocity simulation diagrams",
        caption: "Computational fluid dynamics (CFD) simulation guiding aerodynamic floor profiles.",
      },
      {
        url: "/projects/professional/tower-in-ihsaniye/gallery/PORTFOLYO2025_A330.jpg",
        alt: "Podium stepped terraces and landscape integration",
        caption: "Terraced public podium connecting residential and commercial zones.",
      },
      {
        url: "/projects/professional/tower-in-ihsaniye/gallery/PORTFOLYO2025_A331.jpg",
        alt: "Typical high-rise floor plans",
        caption: "Core efficiency and structural layout across mid and high residential zones.",
      },
      {
        url: "/projects/professional/tower-in-ihsaniye/gallery/PORTFOLYO2025_A332.jpg",
        alt: "Curvilinear facade glazing details",
        caption: "Parametrically panelized curved curtain wall assemblies.",
      },
    ],
    description:
      "Landmark high-rise design in Eyüpsultan, İhsaniye, driven by microclimate wind simulations and public space integration.",
    fullStory:
      "Environmental wind analysis informed the geometry of enclosed and semi-open public spaces. Using Grasshopper and Rhinoceros parametric tools, two primary massing options were refined to maximize comfort at ground level while creating a distinctive city skyline silhouette.",
    technicalSpecs: [
      { label: "Firm", value: "Dilekci Architects (DDA)" },
      { label: "Contribution", value: "Phase I, II - Concept Design" },
      { label: "Program", value: "Mixed Use Tower" },
      { label: "Location", value: "İhsaniye, Istanbul" },
      { label: "Year", value: "2024" },
    ],
    featured: false,
    tags: ["Professional", "Dilekci Architects", "Parametric", "Wind Analysis", "Selected"],
  },
  {
    id: "iris-tower",
    title: "IRIS TOWER",
    slug: "iris-tower",
    category: "professional",
    categories: ["professional", "selected"],
    gridPos: { x: 7, y: 3 },
    subtitle: "Professional - Dilekci Architects DDA — Mixed Use Tower",
    year: "2025",
    location: "Izmir / Bayrakli",
    coverImage: {
      url: "/projects/professional/iris-tower/cover/PORTFOLYO2025_A333.jpg",
      alt: "Iris Tower fractal ink sketch and biomimetic geometry",
      aspectRatio: "16/9",
    },
    gallery: [
      {
        url: "/projects/professional/iris-tower/gallery/PORTFOLYO2025_A333.jpg",
        alt: "Four conceptual proposal renderings",
        caption: "The selected proposal 'IRIS' among four conceptual design iterations.",
      },
      {
        url: "/projects/professional/iris-tower/gallery/PORTFOLYO2025_A334.jpg",
        alt: "Biomimetic fractal pattern diagrams and plant geometry",
        caption: "Fractal geometry derived from natural plant spirals inspiring the facade shell.",
      },
      {
        url: "/projects/professional/iris-tower/gallery/PORTFOLYO2025_A335.jpg",
        alt: "Three structural floor plan configurations",
        caption: "Floor plan typology layout optimized for sweeping Aegean Sea views.",
      },
      {
        url: "/projects/professional/iris-tower/gallery/PORTFOLYO2025_A336.jpg",
        alt: "Unfolded facade panelization matrix",
        caption: "Solar shading analysis and panel angle variation across the facade skin.",
      },
      {
        url: "/projects/professional/iris-tower/gallery/PORTFOLYO2025_A337.jpg",
        alt: "Architectural vertical tower section",
        caption: "Full height section showing core structure, sky terraces, and cantilevered crown.",
      },
    ],
    description:
      "A high-rise tower in Bayraklı, Izmir, exploring biomimetic fractal patterns derived from natural plant geometries.",
    fullStory:
      "Selected as the winning concept among four design proposals presented to the client, IRIS explores how fractal repetition in nature can translate into structural facade panels. The shell facade responds to sea views while optimizing solar shading across all three floor plan configurations.",
    technicalSpecs: [
      { label: "Firm", value: "Dilekci Architects (DDA)" },
      { label: "Contribution", value: "Phase I, II - Concept Design" },
      { label: "Program", value: "Mixed Use Tower" },
      { label: "Location", value: "Bayraklı, Izmir" },
      { label: "Year", value: "2025" },
    ],
    featured: true,
    tags: ["Professional", "Dilekci Architects", "Biomimetic", "Fractal Geometry", "Izmir", "Selected"],
  },
  {
    id: "mavisehir",
    title: "MAVISEHIR",
    slug: "mavisehir",
    category: "professional",
    categories: ["professional", "selected"],
    gridPos: { x: 4, y: 1 },
    subtitle: "Professional - Dilekci Architects DDA — Residential & Landscape Masterplan",
    year: "2023",
    location: "Izmir / Mavişehir",
    coverImage: {
      url: "/projects/professional/mavisehir/cover/cover.png",
      alt: "Folkart Nobilis Mavisehir axonometric massing diagrams",
      aspectRatio: "1/1",
    },
    gallery: [
      { url: "/projects/professional/mavisehir/cover/cover.png", alt: "Axonometric Massing & Typology Studies" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 7.png", alt: "Masterplan Location & Green Infrastructure" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 24.png", alt: "Site Analysis & Urban Settlement Fabric" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 30.png", alt: "Volumetric Massing Evolution Diagram" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 35.png", alt: "Courtyard Perspective & Landscape Corridor" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 37.png", alt: "Residential Block Facade Detail & Terracing" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 38.png", alt: "Inner Garden & Pool Axis View" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 40.png", alt: "Central Swimming Pool & Shaded Promenade Perspective" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 41.png", alt: "Ground Floor Public Promenade & Shaded Canopy" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 42.png", alt: "Terraced Balconies & Vertical Greenery View" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 43.png", alt: "Courtyard Sun Path & Shading Perspective" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 44.png", alt: "Dusk Exterior Lighting Atmosphere" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 45.png", alt: "Pergola & Private Garden Interface" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 46.png", alt: "Upper Floor Terrace View Towards Aegean Sea" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 47.png", alt: "Entrance Plaza & Urban Gate Perspective" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 48.png", alt: "Architectural Screen Wall & Louver Detailing" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 49.png", alt: "Evening Perspective Across Residential Blocks" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 50.png", alt: "Interior Living Room View Towards Garden" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 52.png", alt: "Double Height Living Area & Floor-to-Ceiling Glazing" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 56.png", alt: "Landscape Masterplan Site Plan" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 58.png", alt: "Ground Floor Plan & Circulation Layout" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 59.png", alt: "Upper Floor Typical Residential Apartment Plan" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 66.png", alt: "Typology A Unit Plan & Layout" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 67.png", alt: "Typology B Unit Plan & Layout" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 68.png", alt: "Typology C Unit Plan & Layout" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 69.png", alt: "Typology D Duplex Unit Plan" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 70.png", alt: "Typology E Penthouse Plan" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 71.png", alt: "Building Longitudinal Section" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 75.png", alt: "Building Transverse Section" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 76.png", alt: "Facade Elevation A - Street Front" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 79.png", alt: "Facade Elevation B - Courtyard Front" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 81.png", alt: "Facade Elevation C - Lateral Front" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 82.png", alt: "Facade Elevation D - Rear Front" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 83.png", alt: "Architectural Wall Section Detail 01" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 84.png", alt: "Architectural Wall Section Detail 02" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 85.png", alt: "Parapet & Roof Waterproofing Detail" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 86.png", alt: "Louver & Shading Panel Attachment Detail" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 87.png", alt: "Balcony Drainage & Thermal Break Detail" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 88.png", alt: "Stone Cladding Assembly Detail" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 89.png", alt: "Glazed Curtain Wall Sill Detail" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 90.png", alt: "Underground Parking & Foundation Detail" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 91.png", alt: "Landscape Retaining Wall & Pool Edge Detail" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 92.png", alt: "Site Grading & Stormwater Drainage System" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 93.png", alt: "Material & Finish Schedule" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 94.png", alt: "Solar Radiation & Thermal Simulation Analysis" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 95.png", alt: "Wind Tunnel & Aerodynamic Flow Diagram" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 96.png", alt: "Acoustic Insulation & Noise Mitigation Study" },
      { url: "/projects/professional/mavisehir/gallery/231017_Folkart_Nobilis conv 97.png", alt: "Final Masterplan Isometric Summary" },
    ],
    description:
      "A contemporary residential complex and inner landscape courtyard masterplan in Mavişehir, Izmir, structured around volumetric porosity and coastal microclimate responsiveness.",
    fullStory:
      "Designed at Dilekci Architects (DDA), the project investigates diverse massing typologies to maximize natural daylighting, Aegean coastal breezes, and continuous private/semi-public courtyard transitions. Parametric studies balanced building density with generous garden corridors, shared leisure pools, and shaded colonnades.",
    technicalSpecs: [
      { label: "Firm", value: "Dilekci Architects (DDA)" },
      { label: "Contribution", value: "Concept Design, 3D Modeling & Visualization" },
      { label: "Program", value: "Residential Complex & Landscape Masterplan" },
      { label: "Location", value: "Mavişehir, Karşıyaka, Izmir" },
      { label: "Year", value: "2023" },
    ],
    featured: true,
    tags: ["Professional", "Dilekci Architects", "Residential", "Masterplan", "Izmir", "Selected"],
  },
  {
    id: "urla",
    title: "URLA",
    slug: "urla",
    category: "professional",
    categories: ["professional"],
    gridPos: { x: 1, y: 2 },
    subtitle: "Professional - Dilekci Architects DDA — Low-Rise Residential Settlement & Design Approach",
    year: "2022",
    location: "Izmir / Urla",
    coverImage: {
      url: "/projects/professional/urla/cover/cover.png",
      alt: "Urla Design Approach typological diagrams",
      aspectRatio: "1/1",
    },
    gallery: [
      { url: "/projects/professional/urla/cover/cover.png", alt: "Urla Typological Concept Diagrams" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 8.jpeg", alt: "Masterplan Site Plan & Vehicular Circulation" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 9.jpeg", alt: "Topographic Contours & Parcel Demarcations" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 10.jpeg", alt: "Site Massing & Density Distribution" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 11.jpeg", alt: "Pedestrian Alleyways & Landscape Green Corridors" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 12.jpeg", alt: "Microclimate & Mediterranean Wind Flow Analysis" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 14.jpeg", alt: "Typological Matrix - Unit Variations" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 15.jpeg", alt: "Unit Module 01 - Plan & Section" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 17.jpeg", alt: "Unit Module 02 - Plan & Section" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 18.jpeg", alt: "Unit Module 03 - Plan & Section" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 19.jpeg", alt: "Unit Module 04 - Plan & Section" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 20.jpeg", alt: "Unit Module 05 - Plan & Section" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 21.jpeg", alt: "Unit Module 06 - Plan & Section" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 22.jpeg", alt: "Unit Module 07 - Plan & Section" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 23.jpeg", alt: "Unit Module 08 - Plan & Section" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 24.jpeg", alt: "Unit Module 09 - Plan & Section" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 25.jpeg", alt: "Cluster Organization & Privacy Gradients" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 26.jpeg", alt: "Terraced Courtyard & Water Channel Scheme" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 27.jpeg", alt: "Pergola Shading & Stone Wall Detailing" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 28.jpeg", alt: "Materiality: Local Urla Stone, Wood, & Concrete" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 30.jpeg", alt: "Overall Settlement Axonometric Overview" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 92.jpeg", alt: "Villa Entrance Sequence & Water Feature" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 93.jpeg", alt: "Living Space Opening to Private Pool Terrace" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 94.jpeg", alt: "Semi-Covered Shaded Dining Patio" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 95.jpeg", alt: "Interior Stone Wall & Timber Ceiling Details" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 96.jpeg", alt: "Open Kitchen & Lounge Area Integration" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 98.jpeg", alt: "Master Suite & Private Garden Courtyard" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 100.jpeg", alt: "Bathroom Natural Lighting & Stone Textures" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 101.jpeg", alt: "Exterior Pool View with Reflection Pond" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 102.jpeg", alt: "Sunset Lighting Atmosphere Across Settlement" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 104.jpeg", alt: "Garden Alleyway Flanked by Olive Trees" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 105.jpeg", alt: "Louvered Pergola Light & Shadow Studies" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 106.jpeg", alt: "Stone Wall Apertures & Water Lily Basin" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 107.jpeg", alt: "Floating Stepping Stones & Shaded Walkway" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 108.jpeg", alt: "Courtyard Gathering Space & Bench Inset" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 109.jpeg", alt: "Boundary Wall Integration with Urla Landscape" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 110.jpeg", alt: "Night Atmosphere & Concealed Landscape Lighting" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 111.jpeg", alt: "Detail of Textured Travertine & Rough Stone" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 112.jpeg", alt: "Timber Joinery & Sliding Glazed Partition Details" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 114.jpeg", alt: "Landscape Topography Section Through Olive Grove" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 115.jpeg", alt: "Rainwater Harvesting & Sustainable Ecology Diagram" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 116.jpeg", alt: "Building Envelope Passive Solar Strategy" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 117.jpeg", alt: "Settlement Longitudinal Contour Section" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 118.jpeg", alt: "Settlement Transverse Valley Section" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 120.jpeg", alt: "Physical Context & Aegean Horizon View" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 121.jpeg", alt: "Pedestrian Pathway Tectonic Materiality" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 122.jpeg", alt: "Clubhouse & Communal Facility Design" },
      { url: "/projects/professional/urla/gallery/221007_DesignApproach conv 123.jpeg", alt: "Final Design Approach Conceptual Summary" },
    ],
    description:
      "A low-density residential settlement embedded into Urla's natural topography, exploring modular stone masonry, pergola shading systems, and fluid indoor-outdoor living.",
    fullStory:
      "Developed at Dilekci Architects (DDA), the Urla Design Approach investigates Mediterranean architectural archetypes adapted to modern sustainable living. Individual residential units are terraced along the land contours with stone walls, reflective water surfaces, and timber louvers that provide natural ventilation and sun protection.",
    technicalSpecs: [
      { label: "Firm", value: "Dilekci Architects (DDA)" },
      { label: "Contribution", value: "Concept Design, Architectural Detailing & Visualization" },
      { label: "Program", value: "Low-Rise Residential Settlement" },
      { label: "Location", value: "Urla, Izmir" },
      { label: "Year", value: "2022" },
    ],
    featured: false,
    tags: ["Professional", "Dilekci Architects", "Residential", "Urla", "Mediterranean", "Landscape"],
  },
];

